repos:
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
-   repo: https://github.com/pycqa/flake8
    rev: ''  # pick a git hash / tag to point to
    hooks:
    - id: flake8
      args:
        - "--ignore=E203,E266,E501,W503,F403,F401,E402"
        - "--max-line-length=120"
        - "--max-complexity=10"