parser: '@typescript-eslint/parser'
extends:
  # https://github.com/prettier/eslint-config-prettier
  - prettier
parserOptions: 
  ecmaFeatures: 
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - jest
  - prettier
rules: 
  prettier/prettier:
    - error
    -
      trailingComma: all
      bracketSpacing: true